site_main_homepage:
    pattern:  /
    defaults: { _controller: SiteMainBundle:Main:index }

page_form:
    pattern:  /form
    defaults: { _controller: SiteMainBundle:Main:form}

thanks_page:
    pattern:  /thanks
    defaults: { _controller: SiteMainBundle:Main:thanks}